<?php
echo "<html>";
echo "<head>";
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">";
echo "<title>Postal tariff estimator</title>";
echo "<link rel=\"stylesheet\" type=\"text/css\" href=\"view.css\" media=\"all\">";
echo "<script type=\"text/javascript\" src=\"view.js\"></script>";
echo "</head>";

echo "<body id=\"main_body\" >";
	
echo "<img id=\"top\" src=\"top.png\">";
echo "<div id=\"form_container\">";
			
		include('connection.php');
		
		$country = $_POST['country'];
		$choice = $_POST['choice'];
		$weight = $_POST['weight'];

			
			
			
	if ($choice == "Documentation") {
			if ($weight <= 250) { 
				$query = "select DocumentRate from international_tariff where " . " " . "Country =" . " " . "'" . $country . "'" . " ";
														
												
				$rate = mysql_query($query);
				
			
				while ($i = mysql_fetch_array($rate)) {
					$rti = $i[0];
				
					}
				echo "<b>The system generated response for your query: </b><br>";
				
				echo "Weight : " . $weight . " g <br>";
				echo "Calculated Price : <b>&#8377; " . $rti . "</b>";
				}
			
			else {
				
				$query = "select DocumentRate, DocumentRate1 from international_tariff where " . " " . "Country =" . " " . "'" . $country . "'" . " ";
														
				$rate = mysql_query($query);
				
				while ($i = mysql_fetch_array($rate)) {
					$rti = $i[0];
					$rtiadd = $i[1];
					}
					
				$diff = $weight - 250;
				$temp = $diff/250;
				$amt = $rti + ($rtiadd * $temp);
				echo "<b>The system generated response for your query: </b><br>";
				echo "Weight : " . $weight . " g <br>";
				echo "Calculated Price : <b>&#8377; " . $amt . "</b>";
			}
		}
		
		else if ($choice == "Merchandise") {
			if ($weight <= 250) { 
				$query1 = "select MerchandiseRate from international_tariff where " . " " . "Country =" . " " . "'" . $country . "'" . " ";
	
												
				$rate2 = mysql_query($query1);
				
			
				while ($j = mysql_fetch_array($rate2)) {
					$rti1 = $j[0];
				
					}
				echo "<b>The system generated response for your query: </b><br>";
				echo "Weight : " . $weight . " g <br>";
				echo "Calculated Price : <b>&#8377; " . $rti1 . "</b>";
				}
			
			else {
				
				$query1 = "select MerchandiseRate, MerchandiseRate1 from international_tariff where " . " " . "Country =" . " " . "'" . $country . "'" . " ";
														
				$rate2 = mysql_query($query1);
				
				while ($j = mysql_fetch_array($rate2)) {
					$rti1 = $j[0];
					$rtiadd1 = $j[1];
					}
					
				$diff1 = $weight - 250;
				$temp1 = $diff1/250;
				$amt1 = $rti1 + ($rtiadd1 * $temp1);
				echo "<b>The system generated response for your query:</b><br>";
				echo "Weight : " . $weight . " g <br>";
				echo "Calculated Price : <b>&#8377; " . $amt1 . "</b>";
			}
		}
		
		
		
		
echo "<div id=\"footer\">";
echo "Generated by Technocrats";
echo "</div>";
echo "</div>";
echo "<img id=\"bottom\" src=\"bottom.png\">";
echo "</body>";
echo "</html>";
?>